version: "3"
services:
  app:
    build: "."
    container_name: app
    ports: 
      - "8080"
  nginx:
    build: "./nginx"
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - "app" 